### PR TITLE
Transfer pokemon after a catch

### LINKED ISSUE #180: Low CP/IV Pokemon not recycled after capture
### Expected Behavior

Low value  CP pokemon should be recycled
### Actual Behavior

{'pokemon_potential': 0.7, 'navigator': 'fort', 'cp': 600, u'item_filter': {1: {u'keep': 100}, 2: {u'keep': 100}, 3: {u'keep': 100}, 4: {u'keep': 100}, 101: {u'keep': 10}, 102: {u'keep': 30}, 103: {u'keep': 30}, 201: {u'keep': 30}, 701: {u'keep': 100}}, 'navigator_waypoints': [], 'initial_transfer': True, 'navigator_campsite': None, 'recycle_items': True, 'location_cache': False, 'ign_init_trans': '', 'exclude_plugins': [''], 'fill_incubators': True, use_all_incubators': False, 'distance_unit': u'km', u'mode': u'all', 'debug': False, 'max_steps': 150}
...

2016-08-02 12:44:59] [Catch] A wild Rattata appeared! [CP 164] [Potential 0.69]
[2016-08-02 12:45:01] [Catch] Using Pokeball... (122 left!)
[2016-08-02 12:45:02] [Catch] Rattata has been caught! (CP 164, IV 0.69)
[2016-08-02 12:45:02] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-02 12:45:20] [Catch] A wild Pidgey appeared! [CP 10] [Potential 0.22]
[2016-08-02 12:45:23] [Catch] Using Pokeball... (121 left!)
[2016-08-02 12:45:23] [Catch] Pidgey has been caught! (CP 10, IV 0.22)
[2016-08-02 12:45:23] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-02 12:46:13] [#] Walking from

As you can see no recycle occurred  with pokemon failing under BOTH the IV and the CP limits. 
### Steps to Reproduce

Use master and simply run the box
### Notes

This is one of MANY cases since the refactor where behavior was broken, it should be considered rolling back these changes until that branch can be fixed to be 100% compatible with expected behaviors.
### Other Information

OS:  OSX
Git Commit: 6e22239f214e825d668124aacd570920077b03eb

### PR DESCRIPTION
**Pull request by andythorne**
### Short Description:

Process transfers after a pokemon is caught

Fixes #180 
### Changes:
- Added new events `pokemon_caught`, `pokemon_flee` and `pokemon_catch_failed`
- Fixed a bug in the pokemon potential check calculation

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by wchill** [comment]
Needs rebase.

**Comment by wchill** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/186/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/186/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
rebase please

**Pull request merged**
