### PR TITLE
fixes OBOE, fixes #317

### LINKED ISSUE #317: config parameter does not work
### Expected Behavior

```
python pokecli.py foo/bar/config.yml
```

Loads config from given path if available otherwise throws error complaining about none existent file.
### Actual Behavior

```
python pokecli.py foo/bar/config.yml
```

Throws some out of range index error:

```
pogobot_1  | Traceback (most recent call last):
pogobot_1  |   File "pokecli.py", line 93, in <module>
pogobot_1  |     main()
pogobot_1  |   File "pokecli.py", line 72, in main
pogobot_1  |     config = init_config()
pogobot_1  |   File "pokecli.py", line 54, in init_config
pogobot_1  |     config_path = sys.argv[2]
pogobot_1  | IndexError: list index out of range
```
### Steps to Reproduce

run

```
python pokecli.py foo/bar/config.yml
```
### Other Information

OS: CentOS
Git Commit: 039613290cd859cd88ee822b8da181b4aba5efd6

### PR DESCRIPTION
**Pull request by torvitas**
### Short Description:

see #317 
### Changes:

changes line 51 to fix off-by-one-error and make loading of configuration by parameter possible again
see #317

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by andythorne** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/318/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/318/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by andythorne** [comment]
Actually, this fix is in #270 as well. Makes sense just to close this and merge that when it's done (which is pretty much now).

I'll let someone else confirm.

**Comment by MaxLeiter** [comment]
Agreed, @andythorne 

Thanks for the PR @torvitas :)

**Pull request closed without merging**
