### PR TITLE
Add events to Web plugin

### LINKED ISSUE #123: Map isn't working can anyone help.
### Dropping me in Luxembourg City but the logs are still working but not auto scrolling.

also getting these errors in Terminal.

snip20160730_6
### Run OpenPoGoBot from folder using

python2 pokecli.py -a ptc -u USER -p PASS --location "51.640513, -2.678127"

### LINKED ISSUE #145: Set change size durin iteration
### Expected Behavior

[2016-08-01 10:24:03] [x] PokemonGO Bot v1.0
[2016-08-01 10:24:03] [x] Configuration initialized
[2016-08-01 10:24:03] [Plugins] Loaded plugin "spin_pokestop".
[2016-08-01 10:24:03] [Plugins] Loaded plugin "recycle_items".
[2016-08-01 10:24:03] [Plugins] Loaded plugin "web".
[2016-08-01 10:24:03] [Plugins] Loaded plugin "catch_pokemon".
[2016-08-01 10:24:03] [Plugins] Loaded plugin "transfer_pokemon".
[2016-08-01 10:24:03] [Plugins] Plugins loaded: ['catch_pokemon', 'recycle_items', 'spin_pokestop', 'transfer_pokemon', 'web']
[2016-08-01 10:24:03] [Events] Events available: ['item_bag_full', 'logging', 'pokemon_bag_full', 'pokemon_found', 'pokestop_arrived', 'pokestop_found', 'transfer_pokemon']
[2016-08-01 10:24:03] [x] Fetching altitude from google
...
### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 293, in <module>
    main()
  File "pokecli.py", line 281, in main
    bot.start()
  File "D:\games\OpenPoGoBot\pokemongo_bot__init__.py", line 66, in start
    self._setup_api()
  File "D:\games\OpenPoGoBot\pokemongo_bot__init__.py", line 140, in _setup_api
    self._set_starting_position()
  File "D:\games\OpenPoGoBot\pokemongo_bot__init__.py", line 254, in _set_starting_position
    self._read_config_location()
  File "D:\games\OpenPoGoBot\pokemongo_bot__init__.py", line 260, in _read_config_location
    self.position = self._get_pos_by_name(self.config.location)
  File "D:\games\OpenPoGoBot\pokemongo_bot__init__.py", line 269, in _get_pos_by_name
    logger.log("[x] Fetching altitude from google")
  File "D:\games\OpenPoGoBot\pokemongo_bot\logger.py", line 26, in log
    manager.fire("logging", text=string, color=color, prefix=prefix)
  File "D:\games\OpenPoGoBot\pokemongo_bot\event_manager.py", line 101, in fire
    return self.events[event_name].fire(_args, *_kwargs)
  File "D:\games\OpenPoGoBot\pokemongo_bot\event_manager.py", line 49, in fire
    for listener in self.listeners[priority]:
RuntimeError: Set changed size during iteration
### Steps to Reproduce

I Don't know how to reproduce this bug ..
Sometimes it's error but sometimes not
### Other Information

OS: Windows 8.1
Git Commit: e1bd866e7297663bb236efd719a4122543a4adc5

### PR DESCRIPTION
**Pull request by wchill**
### Short Description:

Adds events to the web plugin for consumption by the web frontend.

State objects are passed directly into the event handlers when the event is fired. To prevent `TypeError: <object> is not JSON serializable` in Python 3 when sending this data over Socket.io, all state objects now inherit from a `JSONEncodable` class which converts all byte strings (`str` in Python 2, `bytes` in Python 3) into a list of `int`.

Unfortunately, as the web frontend still requires refactoring, I have not been able to test the frontend side of things as of yet. Pulling the Socket.io code from OpenPoGoWeb and writing some test JavaScript to ensure that events are properly triggered is encouraged.

Note that the web frontend will require significant changes as the format of the data being passed is different. Also note that some data will be invalid (like PokeStop/gym names) since those require additional API calls which is expensive when passing so much data. This can probably be fixed by implementing a REST API wrapper in the web plugin for this additional data.
### Changes:
- All API state objects extend `JSONEncodable` which converts byte strings into lists of integers, allowing the JSON encoder to work properly under Python 3.
- Added several events to the web plugin (though not all events are currently functional).
- Fixes #145 by making a copy of the list of event handlers before iteration.

Once the web frontend has the relevant changes made, this should also close #123, #124, and #146.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by wchill** [comment]
Here is some test JavaScript that can be used to check the data being sent from the web events. Save this to a `.html` file, open in browser and check the JavaScript console.

```
<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
<script>
var socket_io;
socket_io = io.connect('http://localhost:8000/event');
socket_io.on('connect', function () {
    console.log('connected!');
});
socket_io.on("pokestops", function(msg) {
    console.log("pokestops found");
    console.log(msg);
});
socket_io.on("gyms", function(msg) {
    console.log("gyms found");
    console.log(msg);
});
socket_io.on("nearby_pokemon", function(msg) {
    console.log("pokemon found");
    console.log(msg);
});
socket_io.on("inventory", function(msg) {
    console.log("inventory update");
    console.log(msg);
});
socket_io.on("player", function(msg) {
    console.log("player update");
    console.log(msg);
});
</script>
```

**Comment by MaxLeiter** [comment]
@reaver0 id appreciate your thoughts on this

**Comment by Reaver01** [comment]
I am at work, but I can test it when I get home.

**Comment by 1karu5** [comment]
I will also try to test it and refactor the frontend part if it gets merged

**Comment by andythorne** [comment]
Worth saying @wchill has done some frontend refactoring already: https://github.com/OpenPoGo/OpenPoGoWeb/tree/wchill/refactor

**Comment by wchill** [comment]
Yeah, web is an absolute mess right now.

**Comment by 1karu5** [comment]
Yeah, web is am mess Oo
I think we need to change it step by step.

@wchill The backend is working fine i think. Maybe you should trigger all events on connect? To send the initial state of all objects. After that, working with the events seems to work nicely.
With a few little changes
(mainly https://github.com/OpenPoGo/OpenPoGoWeb/blob/wchill/refactor/js/main.js#L266-L270 to socket_io.on(...) )
 i got the web to display pokestops/gyms and the walking player with your code.

**Comment by wchill** [comment]
@1karu5 can you link me to the diff of your changes?

**Comment by 1karu5** [comment]
https://github.com/1karu5/OpenPoGoWeb/commit/10be22383f9b3589bc57d261973aa58fe53084ae

Was just a quick test...did not have much time. Far away from working, but maybe you could start with it.
We should rewrite this whole ugly main.js ... but maybe step by step, without breaking to much stuff. I think we should finish one rework after the other =)

**Comment by Saturate** [comment]
Could you merge master into this again? Maybe with the UTF-8 fixes, then I'll test it out.

**Comment by Reaver01** [comment]
I would just wait for the Unicode fixes to be merged first though

**Comment by Rlewisrlou666** [comment]
getting this error with the html script test.
snip20160802_2

**Comment by Rlewisrlou666** [comment]
after another update and running again I'm getting no errors in the Java console but i'm not getting any log updates either.

**Comment by wchill** [comment]
@Saturate I've rebased against master. Can't add the Unicode fixes yet.

**Comment by Rlewisrlou666** [comment]
My Java console and Network are saying this with the script.html

snip20160802_4
snip20160802_5

**Comment by wchill** [comment]
It won't say anything while the bot is transferring Pokemon, which might be your issue.

**Comment by Rlewisrlou666** [comment]
how do I check if I am and stop if I am transferring pokemon?

**Comment by wchill** [comment]
This PR is pending a rewrite of the web component.

**Comment by wchill** [comment]
Rebased to use the new API changes.

**Comment by niicojs** [comment]
Hi, I've started playing with events (http://openui.nicontoso.eu), and here is some more info that would be usefull:
- bot initialized sometimes empty (not important but FYI)
- add real location of pokemon caught
- add a pokestop spinned event
- add level in pokemon info object

once this PR is merged, I can do it myself.

**Comment by niicojs** [comment]
Also I've added pokemon_caught event. I'll PR it once this one get merged.

**Comment by tehp** [comment]
@OpenPoGo/maintainers

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/155/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by niicojs** [comment]
Question: on bot_initialized, why sending an array if there is always one element?

**Comment by wchill** [comment]
@nicoschmitt: this was discussed in slack, but it's for if/when multi bot support is added.

**Comment by wchill** [comment]
This PR should be merged ASAP so further refactoring and progress on web UI can continue.

**Comment by tehp** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/155/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by kazyka** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/155/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
