### PR TITLE
Add logging to file

### LINKED ISSUE #289: Logging - File?
I suggest that we add the option to specify a log file.

### PR DESCRIPTION
**Pull request by wchill**
### Short Description:

Now logs all output to `log.txt`. Closes #289.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by niicojs** [comment]
Will this reset the file at each launch?
I would say it should. Unless we want to go into rolling file and such but that's another PR.

**Comment by wchill** [comment]
This only appends to the log file at present.

**Comment by MaxLeiter** [comment]
Can we append the date to the log file?

**Comment by wchill** [comment]
This should be good now.

**Comment by PhilippHeuer** [comment]
Can we also add the username in front of the date? As used in the last location file.
Otherwise i would need to check each file, since i don't know which account they belong to. (running more than one bot)

It doesn't need to be the username, it could also be a "prefix" that will be defined in the config file.

**Comment by wchill** [comment]
On hold; waiting for #286.

**Comment by MaxLeiter** [comment]
Status update @wchill? #286 has been merged :)

**Comment by wchill** [comment]
Gonna need a small refactor to fix conflicts

**Comment by wchill** [comment]
#344 supersedes this; no longer necessary.

**Pull request closed without merging**
