### PR TITLE
Have Git ignore some more stuff

### PR DESCRIPTION
**Pull request by wchill**
Ignore .DS_Store, Thumbs.db, and venv for virtualenv folders.

### CODE REVIEW

**Comment by jtdroste** [comment]
Further down this file, it actually lists `venv` as an ignored folder.

If possible, can you please clean up this as well?  For example, we don't need Distribution / packaging, PyInstaller, (etc...)

👎 

[Rejected with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/14/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by meyer9** [comment]
@jtdroste this is the default python gitignore.

**Comment by jtdroste** [comment]
Yerp.  It has a lot of stuff we don't need.  It's not exactly hurting us, but I like to have things super clean / minimal.  Anyway, now it looks good!

👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/14/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/14/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
