### PR TITLE
Fixed extra commas

### PR DESCRIPTION
**Pull request by meyer9**
Fixed extra commas in example config.json

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
:+1: Thanks :)

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/75/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by kazyka** [comment]
:+1:

**Comment by tehp** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/75/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
Thanks!

**Pull request merged**
