### PR TITLE
Added docs for navigation

### PR DESCRIPTION
**Pull request by andythorne**
### Short Description:

Added docs for navigation

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by jtdroste** [comment]
Should this be a wiki page?

**Comment by andythorne** [comment]
The problem I find with github wikis is that they aren't searchable and aren't updated with PRs.

It also keeps the docs tied to the code, so you can rewind the tree and see the docs for that sha.

I think it's personal preference tho...

**Comment by MaxLeiter** [comment]
I don't think a wiki page could hurt, but I like the idea of keeping them tied to the code via commits
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/185/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/185/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
