### PR TITLE
Moved web to different repo

### PR DESCRIPTION
**Pull request by meyer9**
Short Description: Moved web to different repo

Changes:
- Removed web files from repository
- Initialized submodule under name web pointing to OpenPoGoWeb

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by jtdroste** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/24/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
I'm fine with merging this, but please make another PR modifying the README to have `git clone --recursive` so the submodule is cloned. Will leave for another maintainer to :+1: in case they think the README should be modified in this PR.

**Comment by jtdroste** [comment]
I think that issue will be fixed when we use actual releases - i.e. upload a .zip / .tar.gz

Good catch on the README tho.  Forgot about that.

**Comment by meyer9** [comment]
Fixed.

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/24/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by jtdroste** [comment]
👍

**Comment by jtdroste** [comment]
You'll have to update the branch first.  The update will trigger the review to reset

**Comment by MaxLeiter** [comment]
Almost ready, just squash the commits and this PR should be good to go :)

**Comment by meyer9** [comment]
will squash

**Comment by MaxLeiter** [comment]
Would also really like @Reaver01's +1 on this

**Comment by jtdroste** [comment]
Personally, I don't see that much of a change from @Reaver01's front.  We updated the instructions, so people shouldn't see a difference.

👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/24/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by Reaver01** [comment]
I have thought this was a good idea from the begging. 
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/24/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
LGTM :tada:

**Pull request merged**
