### PR TITLE
Egg Hatching

### PR DESCRIPTION
**Pull request by 1karu5**
### Short Description:

Added egg hatching as suggested in #97 
### Changes:
- added USE_ITEM_EGG_INCUBATOR method to new api wrapper
- created incubator object
- new config option fill_incubators allows incubators filled with new eggs
- dirty little message on success in GET_HATCHED_EGGS

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by wchill** [comment]
There should be an option to only use the unlimited incubator.

**Comment by wchill** [comment]
👍 Looks good to me.

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/125/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
Please add `--fill-incubators` (and `-fi`) to the cli args, and update the README accordingly. Other then that great work!

**Comment by 1karu5** [comment]
done

**Comment by MaxLeiter** [comment]
:+1: awesome! @wchill if you could review this with the new changes as well that'd be great

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/125/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
