### PR TITLE
Feature: Catch lured pokemon

### PR DESCRIPTION
**Pull request by niicojs**
### Short Description:

Catch lured pokemon at Pokestop
### Changes:
- Get info from Pokestop and patch them to catch plugin
- Handle lured pokemon in catch plugin

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by niicojs** [comment]
Need a few more testing

**Comment by MaxLeiter** [comment]
Seems to be working, will let run for a while longer

**Comment by MaxLeiter** [comment]
Can someone else confirm if working? Works fine for me, would like another :+1:

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/346/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/346/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
