### PR TITLE
add web to default exclude plugin

### PR DESCRIPTION
**Pull request by niicojs**
### Short Description:

add web to default exclude plugin
### Changes:
- socket and web don't work well together

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
We need to somehow let users know about the socket map webpage; can you include a print or something with a link?

**Comment by niicojs** [comment]
good idea @MaxLeiter.
the thing is for now it live in a domain I own, I don't really want to keep it that way.
@tehp talked about bying to nice domain. If he don't I'll put mine for the time beeing.

**Comment by tehp** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/243/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/243/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
