### PR TITLE
Config and itemfile need int as key

### PR DESCRIPTION
**Pull request by 1karu5**
### Short Description:

There is a bug causes the bot to not dropping items. The itemobject has ints as keys, the loaded json could only uses strings.

https://github.com/OpenPoGo/OpenPoGoBot/blob/69a376bbf0cec29536a8d466ce4db11949ee7d89/pokemongo_bot/cell_workers/recycle_items_worker.py#L17
This will never get True cause of "1" != 1

Maybe there are problems with pokemon numbers too
### Changes:
- Added "RECYCLE_INVENTORY_ITEM" to the state_manager maps so the request gets fired
- Converted  config's item_filter dict to int keys
- Converted item_list from data/items.json to int keys

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by andythorne** [comment]
I believe this is to be fixed in #129, @wchill?

Update: it's still broken on #129.

**Comment by wchill** [comment]
In #129 I didn't bother trying to fix the item filter; I just set sensible defaults.

**Comment by MaxLeiter** [comment]
:+1: LGTM

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/132/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/132/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
