### PR TITLE
Fix multiple bugs

### LINKED ISSUE #133: Inventory Not Filtering/Recycling
### Expected Behavior

Filter items on login based on config.json file.
Recycle items from stop when item is over limit specified in config.json file.
### Actual Behavior

Not filtering or recycling
### Steps to Reproduce

Normal play
### Other Information

OS: OSX
Git Commit: Master - latest pull from 7/31/16

### LINKED ISSUE #137: Catching Pokemon crash
When catching a Pokemon I am getting the following:

---

[2016-07-31 14:00:48] [Catch] A wild Rhyhorn appeared! [CP 240] [Potential 0.53]
[2016-07-31 14:00:52] [Catch] Ultra Ball stock is low... saving for pokemon with cp greater than 700
Traceback (most recent call last):
  File "pokecli.py", line 260, in <module>
    main()
  File "pokecli.py", line 253, in main
    bot.take_step()
  File "/home/frank/pokemongo_bot/**init**.py", line 74, in take_step
    self.stepper.take_step()
  File "/home/frank/pokemongo_bot/stepper.py", line 41, in take_step
    self._work_at_position(position[0], position[1], True)
  File "/home/frank/pokemongo_bot/stepper.py", line 137, in _work_at_position
    self.bot.work_on_cell(cell, pokemon_only)
  File "/home/frank/pokemongo_bot/__init__.py", line 79, in work_on_cell
    self.fire("pokemon_found", encounters=cell.catchable_pokemon + cell.wild_pokemon)
  File "/home/frank/pokemongo_bot/**init**.py", line 71, in fire
    manager.fire_with_context(event, self, _args, *_kwargs)
  File "/home/frank/pokemongo_bot/event_manager.py", line 107, in fire_with_context
    return self.fire(event_name, _args, *_kwargs)
  File "/home/frank/pokemongo_bot/event_manager.py", line 101, in fire
    return self.events[event_name].fire(_args, *_kwargs)
  File "/home/frank/pokemongo_bot/event_manager.py", line 64, in fire
    return_dict = listener(**listener_args)
  File "./plugins/catch_pokemon/**init**.py", line 89, in pokemon_found
    balls_stock[pokeball] -= 1
KeyError: 0

### LINKED ISSUE #140: Bot stands still?
### Expected Behavior

Bot moving around from pokestop to pokestop
### Actual Behavior

Bot stands still and only catches pokemon since 0db7bf859f155bb922937f469bfce1187c57f767:

> [2016-08-01 01:31:56] [Transfer] No Pokemon to transfer.
> [2016-08-01 01:31:56] [Transfer] Transferred 0 Pokemon.
> [2016-08-01 01:31:56] [#]
> [2016-08-01 01:31:56] [x] Starting PokemonGo Bot....
> [2016-08-01 01:31:57] [Catch] A wild Magikarp appeared! [CP 44] [Potential 0.64]
> [2016-08-01 01:32:01] [Catch] Using Pokeball... (69 left!)
> [2016-08-01 01:32:01] [Catch] Magikarp has been caught! (CP 44, IV 0.64)
> [2016-08-01 01:32:01] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy

Then nothing else happens
Output with ec5b155d6d10047a5d06a9394012fc3017d5787f:

> [2016-08-01 01:36:21] [x] Starting PokemonGo Bot....
> [2016-08-01 01:36:21] [#] Found fort XXXXXXXXXXXXX at distance 0.01km
> [2016-08-01 01:36:21] [#] Moving closer to XXXXXXXXXXXXX
> [2016-08-01 01:36:21] [#] Walking from (XXXXXXXXXXXXX, XXXXXXXXXXXX) to (XXXXXXXX, XXXXXX) for approx. 6.00 seconds
> [2016-08-01 01:36:26] [#] Something rustles nearby!
> [2016-08-01 01:36:26] [] A Wild Staryu appeared! [CP 341] [Potential 0.69]
### Steps to Reproduce

Just start the bot
### Other Information

OS: debian
Git Commit:

### LINKED ISSUE #143: catch pokemon plugin crash
### Expected Behavior

Catching the pokemon !
### Actual Behavior

https://clbin.com/Z9IIG
### Steps to Reproduce

1- The install steps as mentioned in readme.md 
2- run the bot! (with params and with config.json)
## Other Information

OS: Ubuntu 16.04
Git Commit: [latest](https://github.com/OpenPoGo/OpenPoGoBot/tree/d651a5eb3b29cdb972491058d4c07cc9998b07ce)

### LINKED ISSUE #144: Bug Spinning at PokeStop
### Expected Behavior

[PokeStop] Spinning
...
### Actual Behavior

Bug1:
Traceback(most recent call last):
...
./plugins/spin_pokestop/**init**.py line 73

Bug2:
./plugins/recycle_items/**init**.py line 44
### Steps to Reproduce

Bug1:
Just run the bot near the PokeStop

Bug2:
Spinning PokeStop if inventory was full
### How to solve

Bug1:
change str(item_id) to int(item_id) on line 73

Bug2:
change str(item_type) to int(item_type) on line 44
### Other Information

OS: Windows 8.1 with Python 2.7
Git Commit:

### PR DESCRIPTION
**Pull request by wchill**
### Short Description:

Fixes a bug in catching Pokemon when low on Great Balls/Ultra Balls.
Fixes a bug where PokeStops were not being visited.
Fixes a bug in Python 3 where transferring Pokemon would cause an exception.
Fixes use of `iteritems` in Python 3.
Fixes `config.json.example` to be in the proper format.
Fixes egg hatching to only output when an egg is actually hatched.

Closes #140, closes #137, closes #144, closes #143, and closes #133.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
[2016-07-31 21:43:07] [Transfer] Transferred 1 Pokemon.
Traceback (most recent call last):
  File "pokecli.py", line 279, in <module>
    main()
  File "pokecli.py", line 267, in main
    bot.start()
  File "/home/mleiter/Documents/OpenPoGoBot/pokemongo_bot/**init**.py", line 66, in start
    self._setup_api()
  File "/home/mleiter/Documents/OpenPoGoBot/pokemongo_bot/__init__.py", line 189, in _setup_api
    self.fire("item_bag_full")
  File "/home/mleiter/Documents/OpenPoGoBot/pokemongo_bot/__init__.py", line 73, in fire
    manager.fire_with_context(event, self, _args, *_kwargs)
  File "/home/mleiter/Documents/OpenPoGoBot/pokemongo_bot/event_manager.py", line 107, in fire_with_context
    return self.fire(event_name, _args, *_kwargs)
  File "/home/mleiter/Documents/OpenPoGoBot/pokemongo_bot/event_manager.py", line 101, in fire
    return self.events[event_name].fire(_args, *_kwargs)
  File "/home/mleiter/Documents/OpenPoGoBot/pokemongo_bot/event_manager.py", line 64, in fire
    return_dict = listener(**listener_args)
  File "./plugins/recycle_items/**init**.py", line 24, in filter_recyclable_items
    discard_quantity = current_quantity - max_keep_quantity
TypeError: unsupported operand type(s) for -: 'int' and 'dict'

**Comment by wchill** [comment]
Hm, probably related to #132 being merged.

**Comment by ch333** [comment]
Exact same issue as  MaxLeiter.

**Comment by wchill** [comment]
@MaxLeiter @ch333 please insert a `print(bot.config.item_filter)` on line 23 of that file and give me the output.

**Comment by ch333** [comment]
@wchill which file exactly?

**Comment by wchill** [comment]
`File "./plugins/recycle_items/init.py", line 24, in filter_recyclable_items`

**Comment by ch333** [comment]
@wchill I inserted like so in plugins/recycle_items/init.py:

```
    max_keep_quantity = bot.config.item_filter[item_type]
    current_quantity = recyclable_items[item_type]
    print(bot.config.item_filter)
    discard_quantity = current_quantity - max_keep_quantity
```

Same result:
{1: {u'keep': 100}, 101: {u'keep': 0}, 102: {u'keep': 0}, 103: {u'keep': 0}, 104: {u'keep': 45}, 201: {u'keep': 30}, 701: {u'keep': 40}}
Traceback (most recent call last):
  File "pokecli.py", line 279, in <module>
    main()
  File "pokecli.py", line 267, in main
    bot.start()
  File "/Users/ch333/Desktop/POGO/OpenPoGoBot/pokemongo_bot/**init**.py", line 66, in start
    self._setup_api()
  File "/Users/ch333/Desktop/POGO/OpenPoGoBot/pokemongo_bot/__init__.py", line 190, in _setup_api
    self.fire("item_bag_full")
  File "/Users/ch333/Desktop/POGO/OpenPoGoBot/pokemongo_bot/__init__.py", line 73, in fire
    manager.fire_with_context(event, self, _args, *_kwargs)
  File "/Users/ch333/Desktop/POGO/OpenPoGoBot/pokemongo_bot/event_manager.py", line 107, in fire_with_context
    return self.fire(event_name, _args, *_kwargs)
  File "/Users/ch333/Desktop/POGO/OpenPoGoBot/pokemongo_bot/event_manager.py", line 101, in fire
    return self.events[event_name].fire(_args, *_kwargs)
  File "/Users/ch333/Desktop/POGO/OpenPoGoBot/pokemongo_bot/event_manager.py", line 64, in fire
    return_dict = listener(**listener_args)
  File "./plugins/recycle_items/**init**.py", line 25, in filter_recyclable_items
    discard_quantity = current_quantity - max_keep_quantity
TypeError: unsupported operand type(s) for -: 'int' and 'dict'

**Comment by wchill** [comment]
Issue identified, pushing fix shortly.

**Comment by MaxLeiter** [comment]
:+1:  thanks @wchill!

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/141/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by ch333** [comment]
👍👍 Thanks @wchill!  - Works for me too.

**Comment by particle6** [comment]
👍 looks good!!

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/141/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
