### PR TITLE
Cleanup/remove try catch

### LINKED ISSUE #70: Remove all try/catch checks for properties and replace with .get('prop_name', {})
Remove all try/catch checks for properties and replace with .get('prop_name', {})

``` python
try:
    inventory_items = response_dict['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
    for item in inventory_items:
        # print('item {}'.format(item))
        if 'inventory_item_data' in item:
            item_data = item['inventory_item_data']
            if 'pokemon_data' in item_data:
                pokecount += 1
            if 'item' in item_data and 'count' in item_data['item']:
                itemcount += item_data['item']['count']
except KeyError:
    pass
```

### PR DESCRIPTION
**Pull request by meyer9**
Fixes #70

### CODE REVIEW

**Comment by wchill** [comment]
Please also remove `broad-exception` from `.pylintrc`.

**Comment by MaxLeiter** [comment]
:-1: updating the API should be a different PR

[Rejected with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/96/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/96/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/96/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
