### PR TITLE
Initial cleanup pass

### LINKED ISSUE #19: Cleanup of dict accessing
Currently the Bot object inside of **init** is just...terrible when accessing dicts.  This is the first quality of life fix we need to change.

### PR DESCRIPTION
**Pull request by wchill**
Short Description: 
Cleans up `__init__.py` in preparation for refactor.

Changes:
- Fix bad dict usage
- Fix some spacing issues to make some code easier to read

@OpenPoGo/maintainers

Don't merge this yet, still working on it. Alternatively, someone can finish cleaning this up.

Fixes #19

### CODE REVIEW

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/22/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
Please squash the commits; at least remove the merge one

**Comment by meyer9** [comment]
I'll do that.

**Comment by meyer9** [comment]
Done. :+1:

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/22/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by jtdroste** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/22/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
