### PR TITLE
Fix #76

### LINKED ISSUE #76: Don't require config.json
Currently, the bot requires a config.json, otherwise it crashes with
`AttributeError: 'Namespace' object has no attribute 'recycle_items'`, as you can't provide recycle_items via the command line. Ideally, `recycle_items` should be initialized as empty (so to avoid crash if not supplied).

### PR DESCRIPTION
**Pull request by wchill**
### Short Description:

Fix #76 by setting default option and adding command line parameter.
### Changes:
- Sets `recycle_items` to False by default.
- Adds `-ri, --recycle-items` command line parameter.
- Fixes #76.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/79/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: I'd appreciate if you merged this confirming its ready, @wchill

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/79/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by meyer9** [comment]
:-1: wait for #72 

[Rejected with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/79/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
Closing because I will combine this with an implementation for #78.

**Pull request closed without merging**
