### PR TITLE
Refactoring of the Logger

### PR DESCRIPTION
**Pull request by PhilippHeuer**
### Short Description:

I would like to use python's logging lib over the custom functions which are sometimes locally defined, having different names, etc.
### Changes:
- Added ColorLog Dependency
- Removed all local _log or log functions
- Logger now using Debug, Info, Warning, Error and Critical for messages and coloring
- Custom colors for the message's can still be provided
- Refactored all files to use the new logging methods
- Removed LogByEvent Test and FireEvent on Log-Message
- Using TimedRotatingFileHandler FileHandler for log file rotation
- Added option for logging to file in the config
- Customizable Date in the Filename and it's possible to seperate the files into different directories on a per user basis
- Anjusted the Tests
### Preview:

console_new

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by PhilippHeuer** [comment]
This is still unready.

**Comment by PhilippHeuer** [comment]
It's ready now.
I added a deprecation notice, to inform the users about the added logging-sector in the config.yml - It still work's without adding it though.

If you merge this, #346 will also need to be changed to the new logging methods.

**Comment by niicojs** [comment]
This is nice. I can use file logging on my `stealth` branch as I need some more testing and reporting.

**Comment by PhilippHeuer** [comment]
It's ready.

@OpenPoGo/maintainers

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/344/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request closed without merging**
