### PR TITLE
Added Egg incubation

### LINKED ISSUE #160: Egg Hatching
@andythorne 
You deleted the fill incubators part from old WalkTowardsFortWorker object ;)

https://github.com/OpenPoGo/OpenPoGoBot/blob/edc4dddbb58fd029b473cfac827d452b18a2a20d/pokemongo_bot/cell_workers/walk_towards_fort_worker.py#L22

We need to find another place for it.
#97

### PR DESCRIPTION
**Pull request by andythorne**
### Short Description:

Incubate and hatch eggs when needed.

Closes #160 
### Changes:
- `config.incubation_fill`/`-if`/`--incubation-fill` - `True`/`False` to turn incubators on/off
- `config.incubation_use_all`/`-ia`/`--incubation-use-all` - `True`/`False` to use all incubatiors/only unlimited incubator
- `config.incubation_priority`/`-ip`/`--incubation-priority` - array/csv of egg distances to prioritise (`10km,5km,2km`)
- `config.incubation_restrict`/`-ir`/`--incubation-restrict``- dict/csv of egg distances to incubator ids to restrict where eggs are put (`10km=902,5km=902,2km=901`). Omitting a egg distance means no restrictions.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Also please update the README's list of plugins, otherwise looking good :tada:

**Comment by andythorne** [comment]
done :tada:

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/169/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: tested and works great, thanks!

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/169/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
