### PR TITLE
makes transfer_pokemon respect keep: false, fixes #341

### LINKED ISSUE #341: transfer pokemon always_keep
### Expected Behavior

Setting:

```
always_keep:
    Lapras:
        keep: false
```

Should make the plugin not always keep Lapras.
### Actual Behavior

If Lapras is in the config array its always kept, no matter what's in the keep property.
### Steps to Reproduce

Configure keep: false on any pokemon
### Other Information

OS: centos:7
Git Commit: 34dcfc7ac826784ee1305edb55a5fb7d5003aa3d

### PR DESCRIPTION
**Pull request by torvitas**
### Short Description:

see #341
### Changes:
- line 121 in transfer_pokemon to check the property keep instead of just looking if there is something in the array for the pokemon.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
:+1:, but CI is failing 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/342/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by torvitas** [comment]
I see, well I am not much of a python developer, but I guess I understand the problem.

**Comment by meyer9** [comment]
:+1: fix travis

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/342/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by torvitas** [comment]
Although ci passes it looks like I broke the condition.

**Comment by torvitas** [comment]
Just fixed the condition, going to submit a new pull request.

**Pull request merged**
