### PR TITLE
.gitignore: Add encrypt.so and encrypt.o

### PR DESCRIPTION
**Pull request by tegob**
### Short Description:

This adds `encrypt.so` and `encrypt.o` to `.gitignore` so that adding them doesn’t make the tree dirty.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by wchill** [comment]
Hm, it might make more sense to just exclude all *.so and *.o files instead.

**Comment by tegob** [comment]
@wchill Good call. I’ve updated the patch.

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/214/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/214/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by andythorne** [comment]
@tegob Rebase and we'll get it in :+1:

**Comment by tegob** [comment]
@andythorne Rebased!

**Pull request merged**
