### PR TITLE
	Refactor of movement handling

### LINKED ISSUE #92: Feature: Give list of locations
### Expected Behavior

Currently the bot will walk to random locations in a given range, it could be  great to provided an ordered list/dict or locations you want to visit.

--location "53.3468069,-6.2589212"  --destionations=destionations.js

destionations.js

```
destionations = [ 
"53.3457565,-6.2604233"
"53.3448982,-6.2632986"
"53.3442321,-6.2640496"
"53.3430407,-6.2645432"
"53.3444627,-6.2595864"
"53.3444243,-6.2530418"
"53.3422721,-6.2534495"
"53.3434507,-6.2594899"
]
```

This would let people map out their favorite locations within a locale to have the bot visit.

I am looking at writing a Pokemon history system that could then scan the areas for  Pokemon noticed ( similar to pokevision.com but with history).  Over time this would also let the bot be able to have time-based logic such as be @ gps X at 12:20-12:34 to try and get a spawn. Obviously this could use more refinement but initially just being able to have a walk list in the bot would be great.

### PR DESCRIPTION
**Pull request by andythorne**
### Short Description:

See #127 

Closes #92 #127 #138 #147 #148 #152 
### Changes:
- A `Mapper` component will handle map-only functions, like fetching cell IDs from a lat/long coord.
- All movement will be handled by a `Navigator`. The `Navigator` is responsible for choosing where the bot will go. For now, we will have a `FortNavigator` that will visit forts, but any `Navigator` can be easily created, for example something like a `WaypointNavigator` that will walk a pre-set path.
- All pathing (that is HOW you get to the point (coords) a `Navitgator` has choosen) will be done by `PathFinders`. Examples we have now would be a `GoogleDirectionsPathFinder`, which uses the google directions api, and `DirectPathFinder`, which goes directly there.
- The `Stepper` now ONLY handles moving the bot and tracking it's current and origin locations.
#### Available Navigators:
- `fort` (FortNavigator) - Moves between pokestops
- `waypoint` (WaypointNavigator) - Moves between a set of coordinates (`config.navigator_waypoints`)
- `camper` (CamperNavigator) - Camps a set location (`config.navigator_campsite`)
#### New flow:
- `pokecli` invokes the `bot`, `bot` fire any events.
- `bot` requests initial cell ids from the `Mapper`
- `bot` invokes `Navigator` with cell ids
- `Navigator` builds a destination and tells the `Stepper` to move there.
- `Stepper` will find the way there using a `PathFinder`
- `Stepper` will move, 1 step at a time towards location along the `PathFinder`'s path. Each step invokes the `bot` to process a cell (which will handle all the event firing.
- Jumps back to `Navigator` to choose next direction to travel.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by wchill** [comment]
I'm going to cherry-pick your commits into a branch since it's important we get this done ASAP.

**Comment by MaxLeiter** [comment]
@andythorne I invited you as a collaborator with write access, please accept here: https://github.com/OpenPoGo/OpenPoGoBot/invitations

**Comment by wchill** [comment]
@andythorne also please join Slack so we can communicate more easily.

**Comment by wchill** [comment]
This should also close #152.

**Comment by andythorne** [comment]
Right, I think i'm done with this one unless anyone can see something we're missing?

@OpenPoGo/maintainers

**Comment by Reaver01** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/136/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/136/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
