### PR TITLE
Update Travis CI config to use pylint and caching

### PR DESCRIPTION
**Pull request by wchill**
pylint seems to be more comprehensive than pep8, so this PR will have Travis CI use that instead for linting.

In addition, caching is enabled on Travis for pip package installs.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by jtdroste** [comment]
Possibly make it use a wildcard? *.py, rather than specific directories

**Comment by wchill** [comment]
@jtdroste I tried that and it kept going through a lot of junk I didn't want.

**Comment by hoov** [comment]
pep8 is obsolete; it's been renamed to pycodestyle. also, is flake8 not good enough? i find it beyond sufficient.

**Comment by tehp** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/40/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/40/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
