### PR TITLE
Update Travis config and gitignore, make bot work under Python3

### PR DESCRIPTION
**Pull request by wchill**
### Changes:
- Added vim swap files (`*.swp`) to `.gitignore`
- Made Travis run the bot for five minutes using a dummy account to see if output is as expected
### TODO:
- [ ] Make bot work under Python3.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by sniok** [comment]
👍

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/62/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
:-1: until Travis passes Python3.

[Rejected with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/62/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by meyer9** [comment]
Needs fixes.

**Pull request closed without merging**
