### PR TITLE
Made sure all python code was PEP-8 compliant

### PR DESCRIPTION
**Pull request by meyer9**

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Looks good to me :+1:

**Comment by meyer9** [comment]
This branch is ready to merge.

**Comment by meyer9** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/7/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by jtdroste** [comment]
It looks like some lines are super long in pokecli.py - I think they're above 80chars

**Comment by kazyka** [comment]
:+1:

**Comment by meyer9** [comment]
I disabled that because sometimes it screws up the code and makes it less readable.

**Comment by jtdroste** [comment]
Okay.

👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/7/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by jtdroste** [comment]
👍

**Comment by jtdroste** [comment]
Merged.  Plus we had fun testing our pullapprove!

**Pull request merged**
