### PR TITLE
Move to YAML for config files, use per-plugin YAML config files

### PR DESCRIPTION
**Pull request by wchill**
### Short Description:

`config.json` has always been kind of an unwieldy way to specify configuration settings, especially since JSON does not support comments. In addition, this will mark a shift away from using CLI parameters for most advanced options to declutter `pokecli.py`.

This PR introduces the `config` folder which houses `config.yml` - this contains all the necessary settings for the bot itself to operate. It also introduces `config/plugins` which houses YAML config files for each individual plugin. This should allow for proper modularization since plugins will no longer require access to the bot's global configuration, only its own individual configuration.

`config.yml` must be specified explicitly on the command line; it does not need to be housed in `config` and does not need to be named `config.yml`. In addition, `config/plugins` can be set to another folder by modifying `config.yml`.

This PR also removes `proto` and `setup.py` since they are currently not being used.

More complicated JSON files can first be translated into YAML using http://www.json2yaml.com and then properly formatted/commented.
### Changes:
- Move to YAML over JSON for configuration
- Use per-plugin config files for better modularity and version control
- Some repo cleanup

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by andythorne** [comment]
So much yes. Can't wait for this!

**Comment by MaxLeiter** [comment]
Definitely a fan of this overall, however I'd like for there to be some sort of log/message if JSON files are found notifying the user we've switched to YAML (and maybe a link to a wiki page or something)

**Comment by wchill** [comment]
Yep @MaxLeiter I feel like the best way is to continue supporting JSON for a week or so while printing a deprecation message, then remove the JSON support entirely.

**Comment by wchill** [comment]
Note that test failure is expected. There's no point fixing the failed tests at the moment since the bot runs fine and #270 needs to be merged before tests can be fixed.

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/286/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by tehp** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/286/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
