### PR TITLE
Added unit tests for navigatiors and path_finders.

### PR DESCRIPTION
**Pull request by andythorne**
### Short Description:

Added unit tests for navigatiors and path_finders.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by andythorne** [comment]
Just a note, I'm not a primarily a python dev and don't have much experience writing unit and functional tests for python projects.

Feedback here would be much appreciated :)

**Comment by wchill** [comment]
Think you can also run the unit tests on Travis?

**Comment by andythorne** [comment]
They do :)

**Comment by wchill** [comment]
Ah, I just noticed that. Cool

**Comment by wchill** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/215/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by tehp** [comment]
👍 
Looks good, you just need to rebase. 😄 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/215/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wongjustin98** [comment]
Change `format_time(len(destination.steps))),` to `format_time(len(destination._steps))),` in stepper.py

Looks like you renamed the variable on destination without changing all usages of it.

**Comment by andythorne** [comment]
Thanks @registered99 , fixed in #227

**Pull request merged**
