### PR TITLE
add pokemon settings for evolution logic

### PR DESCRIPTION
**Pull request by niicojs**
### Short Description:

add pokemon settings for evolution logic
can tell you family id, candy to evolve, etc... 
data is ask to the server to be up to date
### Changes:
- respond to pokemon_settings event and send pokemon_settings 

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by niicojs** [comment]
@wchill As you'll see I had to set cache to false to make it work.
It would be better if cache works as it is a pretty big chunk of data to get.

**Comment by MaxLeiter** [comment]
Do we want to look into the cache issue and then merge this?

**Comment by niicojs** [comment]
Let's see if wchill has an obvious fix for the cache.

**Comment by wchill** [comment]
👍 waiting for CI to clear

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/287/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: woot

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/287/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
