### PR TITLE
Fix backwards transfer logic

### LINKED ISSUE #301: Inital Transfer Questions
Sorry if this is a noob question.  I can't seem to find answers in the documentation at all....

Is there a way to pass the ignore transfer list from the config.json file?  
Something like: `"ign-init-trans": [002,003,005],`.  I can't get to to work.  I've tried including the list in [...], {....}, (...), and just the straight list.  I always get the error: `ERROR:root:Error loading config.json`
Update: It will read the config.json file if I use: `"[002,003,005]",`, but does not add them to the exclude list.  It lists :'ign_init_trans': '', and u'ign-init-trans': u'002,003,005', in the inital print out.

Also, I'm confused how the transfer_pokemon.json file works.  With the "and" logic, it should only transfer a Pokemon below the CP-limit AND below the IV-limit, correct?  After yesterday's commit, I changed the "and" to "or" (after losing some great Pokemon) and it seemed to save duplicates with higher IVs OR higher CPs.  After today's commit, it transferred a bunch of duplicates with lower CPs, but with IVs in the 90+.

At the moment, it seems to transfer any duplicate.  The only way to stop it is to pass in a bunch of exceptions in the command line `-ign [002,003,005,...],`, but then it doesn't seem to transfer any Pokemon at all.

### PR DESCRIPTION
**Pull request by wchill**
### Short Description:

The fix in #298 was backwards. This should properly fix it. To clear up confusion, we no longer skip a loop iteration but instead just add a Pokemon to the list if a condition is met.
### Changes:
- Moved individual filters into separate functions instead of putting them all in one function.
- Fixed logic from #298.
- Add unit tests for the refactored filters.

Closes #301.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/305/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
Actually, don't merge yet as I'm opting to rewrite the transfer plugin instead.

**Comment by niicojs** [comment]
I had a PR about to be sent around not transferring favorites if you could add it to the refactoring.
Setting favorite is almost ready in the ui so users can favorite them to be sure they are not transfered no matter the rules.

**Comment by wchill** [comment]
@nicoschmitt added some code for that.

**Comment by wchill** [comment]
Ready to merge. Note that unit tests will need rework if #270 is merged first.

**Comment by andythorne** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/305/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
