### PR TITLE
only check for "location" if "location_cache" is false

### LINKED ISSUE #88: [bug] Location Cache Not Used | config.json -> location_cache: true
### Expected Behavior

Bot starts from last recorded location specified in `data/last-location-{username}.json`
### Actual Behavior

Bot starts at specified location from config,json
### Steps to Reproduce
- Run bot with config.json settings:

``` json
"location": "123 Sesame Street",
"location_cache": true,
```
- wait for bot to move away from location
- restart bot
### Other Information

OS: Windows 10
Git Commit: [newest | master | @ 4:20pm (GMT+12)](https://github.com/OpenPoGo/OpenPoGoBot/tree/f6af4cbd6adb3aa37365f0a04e9e7f5302182347)

### PR DESCRIPTION
**Pull request by epicblood**
### Short Description:

don't override location cache.

fixes #88 

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by jmeyer2k** [comment]
:+1: but this also needs to be done with other properties.

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/89/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by kazyka** [comment]
:+1:

**Comment by MaxLeiter** [comment]
:+1: nice catch 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/89/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
