### PR TITLE
fixed readme and example config

### PR DESCRIPTION
**Pull request by 1karu5**
### Short Description:

Wrong (old) param names

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Thanks for catching this
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/172/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by andythorne** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/172/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by andythorne** [comment]
@1karu5 Rebase and we'll get this in :)

**Comment by Saturate** [comment]
Awesome :)

**Pull request merged**
