### PR TITLE
manual transfer and evolve

### PR DESCRIPTION
**Pull request by niicojs**
### Short Description:

manual transfer and evolve through UI
### Changes:
- add new actions from UI

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by andythorne** [comment]
I don't think we should be evolving and releasing inside a socket plugin, it should all be done by the `evolver` and `transfer_pokemon` plugins.

I've been working on #117 to do this already. Once that's finished (this evening sometime) the socket plugin can just fire a single event or evolve or release

**Comment by niicojs** [comment]
I'm not sure @andythorne.
For example, If I prefer transfering pokemon manually, I'll disable the transfer plugin, so it does not make much sense to call it from there.
But I agree that ideally we should have a center "evolve" and "transfer" method that all plugin should call.

**Comment by andythorne** [comment]
But surely if you disable the `transfer_pokemon` plugin, you don't want to do transfers? I can foresee it causing confusion if people turn off the `transfer_pokemon` plugin, but they can still be transferred through the UI?

**Comment by wchill** [comment]
Well, if you don't want _automated_ transfers, it makes sense to disable the `transfer_pokemon` plugin.

**Comment by andythorne** [comment]
Maybe the module names should be changed to make it more obvious what it does. I really think we need a central place for actions tho. calling `bot.api_wrapper.release_pokemon(...).call()` whenever we want is going to create problems, for example with inconsistent sleep times post-action.

**Comment by niicojs** [comment]
agree with you @andythorne but not in this PR :)

**Comment by tehp** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/244/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: LGTM

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/244/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
