### PR TITLE
Add web frontend plugin

### PR DESCRIPTION
**Pull request by wchill**
### Short Description:

This adds WebSocket support and removes the need to run `python -m SimpleHTTPServer 8000`.
### Changes:
- Move to Flask for web server.
- Adds a `logging` event that passes two arguments, `output` with the line output and `color` with the output color.
- Begin implementation of Flask-SocketIO event handlers to expose data to web frontend.
- Fixes #77.

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Is this ready to be reviewed?

**Comment by meyer9** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/72/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
Works for me, but do we want it to be a commandline/config option? --web perhaps? In case people don't want to spend the resources on it if they won't use it?

**Comment by meyer9** [comment]
no, I'm creating a new issue for this. #78

**Comment by MaxLeiter** [comment]
I'm going to approve this, but ultimately @wchill should merge it.

:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/72/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
