### PR TITLE
Add evolutions on catch and transfer.

### PR DESCRIPTION
**Pull request by epicblood**
### Short Description:

Evolve pokemon when possible.
Relies on #155 as api_wrapper doesn't have evolution call yet.
### Changes:
- add pokemon_caught event
- add pokemon_fled event
- add after_transfer_pokemon event
- add evolver plugin
- add evolve_pokemon to config
- add evolve_filter to config

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by Saturate** [comment]
Would be interesting if it could just pop a lucky egg, and then evovle all pokemons, this way we gain a lot of XP.

**Comment by kazyka** [comment]
instead of numbers, I think it should be names

**Comment by epicblood** [comment]
@Saturate that can be done in a later PR, as lucky eggs will likely be their own plugin. You'd have to decide when to use a lucky egg, under what conditions, etc so will likely involve a lot of config options

@kazyka Noted. That's how I had it at first, but I decided to change to ID as everything else inside the bot uses ID. I can change it back if others prefer that as well.

**Comment by kazyka** [comment]
@epicblood think you should go with names. It is easier to remember a name, than the ID of the pokemon and then just .lowercase() that, so it won't matter if the user types with lowercase letter or not

**Comment by epicblood** [comment]
@kazyka I also added 'all' as a possibility

**Comment by niicojs** [comment]
after_transfer_pokemon should pass the pokemon object, not just the name (to pass info to web if needed)

**Comment by tehp** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/194/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by MaxLeiter** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/194/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Pull request merged**
