### PR TITLE
Cache Item Templates locally

### PR DESCRIPTION
**Pull request by niicojs**
### Short Description:

mimic real app for item templates
### Changes:
- startup call api should look more like the real app
- use timestamp from config version to get item templates and cache it
- only download item templates if newer than cache version

@OpenPoGo/maintainers

cache response and don't always ask for it, like the real app

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Failed for me on Windows 7 Python3, looking into real quick

**Comment by niicojs** [comment]
New commit, I'm using latest version of the pogapi with correct device_info.
Works for me on python 2.7, but breaks Travis.

I'll try to use @wchill branch but I need some more info on what is expected from signature.

**Comment by wchill** [comment]
Note that I basically reverted the change in pgoapi with the new `signature-info` branch that I made earlier; PGoApi now expects you to build your own Signature object with the relevant unknown6 fields pre-filled. (PGoApi will handle the signing/hashing for you.)

Take a look at https://github.com/PokemonGoF/PokemonGo-Bot/blob/1084614dd2b5940b67abec9969f5d9d5047407de/pokemongo_bot/api_wrapper.py for an example of usage.

**Comment by niicojs** [comment]
Yes, saw that and tried but I was lacking the example on how to generate the signature. I'll have a look later.

**Comment by niicojs** [comment]
I'm gonna close this one as I'm refactoring the bot to look more like the real app

**Pull request closed without merging**
