### PR TITLE
Refactored the stepper to reduce recursion levels

### PR DESCRIPTION
**Pull request by andythorne**
### Short Description:

Refactored the stepper to reduce recursion levels.
### Changes:
- Bot now handles step progression rather than stepper
#### New flow:

```
>bot requests a list destinations from the navigator
    > bot loops each destination and asks stepper to work out all the required steps to get to a destination
        > stepper asks the path finder how to get to the destination and returns a list of steps
    > the bot injects the list of steps into the destination
    > the bot tells the step progress every step
        > after every step, the botter calls fires events of the pokemon and pokestops at the new location
```

@OpenPoGo/maintainers

### CODE REVIEW

**Comment by wchill** [comment]
👍 Looks fine, just fix that one pylint error.

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/183/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by wchill** [comment]
Also note that there is a small regression in bot performance, but this can be fixed in another PR.

**Comment by MaxLeiter** [comment]
Could the docs be added in a separate PR?

**Comment by andythorne** [comment]
Yeah sure, 1 sec.

Edit: Done.

**Comment by MaxLeiter** [comment]
:+1: thanks!

[Approved with PullApprove](https://pullapprove.com/OpenPoGo/OpenPoGoBot/pull-request/183/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=OpenPoGo/OpenPoGoBot)

**Comment by andythorne** [comment]
Not sure what when on with that commit message lol

**Pull request merged**
